"""
py2app build script for Loadscope.

Run from the project folder:
    /usr/bin/python3 setup.py py2app

The output goes to dist/Loadscope.app. That .app is fully self-contained —
Python interpreter, PyQt5, openpyxl, and the workbook template are all
bundled inside.

For a friend-shippable build, zip the .app afterward and AirDrop or email it.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path
from setuptools import setup

HERE = Path(__file__).resolve().parent

# ---------------------------------------------------------------------------
# Workaround for macOS provenance xattr blocking py2app builds.
#
# On recent macOS versions, the OS attaches `com.apple.provenance` to files
# copied by certain process contexts (Terminal-launched .command, Finder
# double-clicks). That xattr later blocks py2app/macholib from modifying the
# same files (Python3 framework binary, .dylibs) — manifesting as
# `[Errno 1] Operation not permitted` during the changefunc/load-command
# rewrite phase.
#
# We can't prevent the xattr from being added, but we can strip it as soon
# as a file is copied. Wrap shutil.copy / copy2 / copyfile so every copy
# inside py2app's run is followed by a best-effort xattr removal.
# ---------------------------------------------------------------------------

def _strip_provenance(path):
    try:
        subprocess.run(
            ["/usr/bin/xattr", "-d", "com.apple.provenance", str(path)],
            stderr=subprocess.DEVNULL,
            check=False,
        )
    except Exception:
        pass

def _wrap_copy(orig):
    def wrapped(src, dst, *args, **kwargs):
        result = orig(src, dst, *args, **kwargs)
        try:
            target = dst
            if os.path.isdir(target):
                target = os.path.join(target, os.path.basename(src))
            _strip_provenance(target)
        except Exception:
            pass
        return result
    return wrapped

shutil.copy2 = _wrap_copy(shutil.copy2)
shutil.copy = _wrap_copy(shutil.copy)
shutil.copyfile = _wrap_copy(shutil.copyfile)

# Make app/ importable so py2app's static analysis can discover all the
# submodules referenced from main.py.
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "app"))

APP_DISPLAY_NAME = "Loadscope"
APP_BUNDLE_ID = "com.chadheidt.loadscope"
APP_VERSION = "0.14.1"  # keep in sync with app/version.py

# The main entry script
ENTRY = ["app/main.py"]

# Files placed in <App.app>/Contents/Resources/
TEMPLATE_PATH = HERE / "Rifle Loads Template (do not edit).xltx"
DATA_FILES = []
if TEMPLATE_PATH.exists():
    DATA_FILES.append(str(TEMPLATE_PATH))
else:
    print(f"WARNING: template not found at {TEMPLATE_PATH} — the bundle will ship without it.")

# Bundle the marketing icon + screenshot so the license dialog can show them
# while the app is locked. license_dialog.py looks for them in
# Contents/Resources/ at runtime.
ICON_PNG = HERE / "docs" / "assets" / "icon.png"
SCREENSHOT_PNG = HERE / "docs" / "assets" / "screenshot.png"
for p in (ICON_PNG, SCREENSHOT_PNG):
    if p.exists():
        DATA_FILES.append(str(p))

# v0.14 demo mode: bundle the pre-populated demo workbook so the guided tour
# has something to walk through before the user picks their own workbook.
# Generated by tools/generate_demo_workbook.py — re-run that whenever the
# realistic data needs to be refined.
DEMO_WORKBOOK = HERE / "app" / "resources" / "Loadscope - Demo Workbook.xlsx"
if DEMO_WORKBOOK.exists():
    DATA_FILES.append(str(DEMO_WORKBOOK))
else:
    print(f"WARNING: demo workbook missing at {DEMO_WORKBOOK} — run "
          f"tools/generate_demo_workbook.py before building the .app")

# v0.14: bundle the Quick Start .docx so setup_wizard can copy it into
# the user's project folder on first launch (Chad 2026-05-14: the Start
# Here footer pointed users to "your project folder" but the docx never
# actually landed there — only in the Downloads ZIP).
QUICKSTART_DOCX = HERE / "Loadscope — Quick Start.docx"
if QUICKSTART_DOCX.exists():
    DATA_FILES.append(str(QUICKSTART_DOCX))
else:
    print(f"WARNING: Quick Start docx missing at {QUICKSTART_DOCX} — the "
          f".app will ship without it.")

# Also bundle import_data.py so the app can call into it
IMPORT_DATA_PATH = HERE / "import_data.py"

# Use the generated .icns icon if it exists, fall back to default otherwise
ICON_PATH = HERE / "app" / "resources" / "AppIcon.icns"
ICONFILE = str(ICON_PATH) if ICON_PATH.exists() else None

OPTIONS = {
    "argv_emulation": False,
    # Build target: x86_64 (Intel). Runs natively on Intel Macs and via
    # Rosetta 2 on Apple Silicon. Tried universal2 in v0.8.4 but PyQt5
    # came in arm64-only because pip on the macos-latest CI runner pulled
    # the arm64-specific wheel even when the launcher was universal. See
    # build-mac.yml header for full reasoning.
    "iconfile": ICONFILE,  # generated by Generate Icon.command
    "plist": {
        "CFBundleName": APP_DISPLAY_NAME,
        "CFBundleDisplayName": APP_DISPLAY_NAME,
        "CFBundleIdentifier": APP_BUNDLE_ID,
        "CFBundleVersion": APP_VERSION,
        "CFBundleShortVersionString": APP_VERSION,
        "CFBundleExecutable": APP_DISPLAY_NAME,
        # Force the bundle's primary language to English. Without this, py2app
        # sometimes inherits a different default region from the bundled Qt
        # frameworks which can cause dialog buttons/menus to show in Spanish.
        "CFBundleDevelopmentRegion": "en",
        "CFBundleLocalizations": ["en"],
        "LSMinimumSystemVersion": "10.13",
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "NSHumanReadableCopyright": "Built for personal use.",
        # Declare that this app handles CSV files. macOS uses this to:
        #   1. Allow drag-and-drop of CSVs onto the Dock icon
        #   2. Show this app in "Open With…" right-click menus on CSV files
        #   3. Optionally let the user set this as the default CSV opener
        # When files arrive this way, the app receives QFileOpenEvent(s)
        # which are intercepted by the App class in app/main.py.
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeName": "CSV File",
                "CFBundleTypeRole": "Viewer",
                "LSItemContentTypes": ["public.comma-separated-values-text"],
                "CFBundleTypeExtensions": ["csv"],
                "LSHandlerRank": "Alternate",
            },
        ],
        # Custom URL scheme: clickable workbook hyperlinks (e.g. on
        # Charts!A10 'Reset Composite Weights') open the loadscope://
        # scheme, which macOS routes to this app. The app translates the
        # URL into an in-app action (e.g. trigger the reset-weights flow).
        # Handler: RifleLoadApp.event() in app/main.py inspects
        # QFileOpenEvent.url() for the 'loadscope' scheme.
        "CFBundleURLTypes": [
            {
                "CFBundleURLName": "Loadscope URL",
                "CFBundleURLSchemes": ["loadscope"],
            },
        ],
    },
    # Bundle these top-level packages in full
    "packages": ["PyQt5", "openpyxl", "parsers"],
    # Bundle these individual modules from app/ and the project root
    "includes": [
        "csv_router",
        "config",
        "setup_wizard",
        "updater",
        "installer",
        "version",
        "theme",
        "import_data",
        "disclaimer",
        "license",
        "license_dialog",
        "settings_dialog",
        "load_card",
        "pocket_card",
        "load_sharing",
        "crash_reporter",
        "help_dialog",
        "new_cycle_dialog",
        "welcome_tutorial",
    ],
    "excludes": [
        # Reduce bundle size — exclude things py2app might pull in that we don't need
        "tkinter",
        "matplotlib",
        "numpy.tests",
        # Pillow is only used by tools/render_*.py for marketing-site hero images,
        # not by the runtime app. openpyxl's optional `from PIL import Image` makes
        # py2app pull it in by default, which both bloats the bundle and (on some
        # macOS versions) trips an EPERM on the bundled libtiff/libjpeg dylibs.
        "PIL",
    ],
}

setup(
    name=APP_DISPLAY_NAME,
    app=ENTRY,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
