"""
py2app build script for Cold Bore.

Run from the project folder:
    /usr/bin/python3 setup.py py2app

The output goes to dist/Cold Bore.app. That .app is fully self-contained —
Python interpreter, PyQt5, openpyxl, and the workbook template are all
bundled inside.

For a friend-shippable build, zip the .app afterward and AirDrop or email it.
"""

import sys
from pathlib import Path
from setuptools import setup

HERE = Path(__file__).resolve().parent

# Make app/ importable so py2app's static analysis can discover all the
# submodules referenced from main.py.
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "app"))

APP_DISPLAY_NAME = "Cold Bore"
APP_BUNDLE_ID = "com.chadheidt.coldbore"
APP_VERSION = "0.8.1"  # keep in sync with app/version.py

# The main entry script
ENTRY = ["app/main.py"]

# Files placed in <App.app>/Contents/Resources/
TEMPLATE_PATH = HERE / "Rifle Loads Template (do not edit).xltx"
DATA_FILES = []
if TEMPLATE_PATH.exists():
    DATA_FILES.append(str(TEMPLATE_PATH))
else:
    print(f"WARNING: template not found at {TEMPLATE_PATH} — the bundle will ship without it.")

# Also bundle import_data.py so the app can call into it
IMPORT_DATA_PATH = HERE / "import_data.py"

# Use the generated .icns icon if it exists, fall back to default otherwise
ICON_PATH = HERE / "app" / "resources" / "AppIcon.icns"
ICONFILE = str(ICON_PATH) if ICON_PATH.exists() else None

OPTIONS = {
    "argv_emulation": False,
    "iconfile": ICONFILE,  # generated by Generate Icon.command
    "plist": {
        "CFBundleName": APP_DISPLAY_NAME,
        "CFBundleDisplayName": APP_DISPLAY_NAME,
        "CFBundleIdentifier": APP_BUNDLE_ID,
        "CFBundleVersion": APP_VERSION,
        "CFBundleShortVersionString": APP_VERSION,
        "CFBundleExecutable": APP_DISPLAY_NAME,
        # Force the bundle's primary language to English. Without this, py2app
        # sometimes inherits a different default region from the bundled Qt
        # frameworks which can cause dialog buttons/menus to show in Spanish.
        "CFBundleDevelopmentRegion": "en",
        "CFBundleLocalizations": ["en"],
        "LSMinimumSystemVersion": "10.13",
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "NSHumanReadableCopyright": "Built for personal use.",
        # Declare that this app handles CSV files. macOS uses this to:
        #   1. Allow drag-and-drop of CSVs onto the Dock icon
        #   2. Show this app in "Open With…" right-click menus on CSV files
        #   3. Optionally let the user set this as the default CSV opener
        # When files arrive this way, the app receives QFileOpenEvent(s)
        # which are intercepted by the App class in app/main.py.
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeName": "CSV File",
                "CFBundleTypeRole": "Viewer",
                "LSItemContentTypes": ["public.comma-separated-values-text"],
                "CFBundleTypeExtensions": ["csv"],
                "LSHandlerRank": "Alternate",
            },
        ],
    },
    # Bundle these top-level packages in full
    "packages": ["PyQt5", "openpyxl", "parsers"],
    # Bundle these individual modules from app/ and the project root
    "includes": [
        "csv_router",
        "config",
        "setup_wizard",
        "updater",
        "installer",
        "version",
        "theme",
        "import_data",
        "disclaimer",
        "settings_dialog",
        "load_card",
        "load_sharing",
        "crash_reporter",
        "help_dialog",
        "new_cycle_dialog",
        "welcome_tutorial",
    ],
    "excludes": [
        # Reduce bundle size — exclude things py2app might pull in that we don't need
        "tkinter",
        "matplotlib",
        "numpy.tests",
    ],
}

setup(
    name=APP_DISPLAY_NAME,
    app=ENTRY,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
